export const data = [
  {
    id: 1,
    title: "Lira Earrings",
    currency: "$",
    price: 20.00,
    img: '/images/Img01.jpg',
    category_id: 1,
    SKU: "EL712",
    material: "Metal",
    dimentions: "15cm x 10cm x 1cm",
    weight: "0.03kg",
    colours: "Gold"
  },
  {
    id: 2,
    title:'Hal Earrings',
    currency: "$",
    price: 25.00,
    img: '/images/Img02.jpg',
    category_id: 1,
    SKU: "EH102",
    material: "Metal",
    dimentions: "15cm x 5cm x 1cm",
    weight: "0.02kg",
    colours: "Gold"
  },
  {
    id: 3,
    title:'Kaede Hair Pin Set Of 3 ',
    currency: "$",
    price: 30.00,
    img: '/images/Img03.jpg',
    category_id: 3,
    SKU: "HS314",
    material: "Metal",
    dimentions: "10cm x 3cm x 1cm",
    weight: "0.01kg",
    colours: "Gold, White"
  },
  {
    id: 4,
    title:'Hair Pin Set of 4',
    currency: "$",
    price: 30.00,
    img: '/images/Img04.jpg',
    category_id: 3,
    SKU: "HS412",
    material: "Metal",
    dimentions: "10cm x 3cm x 1cm",
    weight: "0.01kg",
    colours: "Gold, White"
  },
  {
    id: 5,
    title:'Plaine Necklace',
    currency: "$",
    price: 19.00,
    img: '/images/Img05.jpg',
    category_id: 4,
    SKU: "NK722",
    material: "Metal",
    dimentions: "2cm x 2cm x 1cm",
    weight: "0.01kg",
    colours: "Gold, Black"
  },
  {
    id: 6,
    title:'Yuki Hair Pin Set of 3',
    currency: "$",
    price: 29.00,
    img: '/images/Img06.jpg',
    category_id: 3,
    SKU: "HS325",
    material: "Metal",
    dimentions: "10cm x 1cm x 1cm",
    weight: "0.01kg",
    colours: "Gold, Ruby"
  },
]
