<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = now();

        $products = [
            [
                'id' => 1,
                'title' => 'Lira Earrings',
                'currency' => '$',
                'price' => 20.00,
                'img' => '/images/Img01.jpg',
                'category_id' => 1,
                'SKU' => 'EL712',
                'material' => 'Metal',
                'dimensions' => '15cm x 10cm x 1cm',
                'weight' => '0.03kg',
                'colours' => 'Gold',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 2,
                'title' => 'Hal Earrings',
                'currency' => '$',
                'price' => 25.00,
                'img' => '/images/Img02.jpg',
                'category_id' => 1,
                'SKU' => 'EH102',
                'material' => 'Metal',
                'dimensions' => '15cm x 5cm x 1cm',
                'weight' => '0.02kg',
                'colours' => 'Gold',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 3,
                'title' => 'Kaede Hair Pin Set Of 3',
                'currency' => '$',
                'price' => 30.00,
                'img' => '/images/Img03.jpg',
                'category_id' => 3,
                'SKU' => 'HS314',
                'material' => 'Metal',
                'dimensions' => '10cm x 3cm x 1cm',
                'weight' => '0.01kg',
                'colours' => 'Gold, White',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 4,
                'title' => 'Hair Pin Set of 4',
                'currency' => '$',
                'price' => 30.00,
                'img' => '/images/Img04.jpg',
                'category_id' => 3,
                'SKU' => 'HS412',
                'material' => 'Metal',
                'dimensions' => '10cm x 3cm x 1cm',
                'weight' => '0.01kg',
                'colours' => 'Gold, White',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 5,
                'title' => 'Plaine Necklace',
                'currency' => '$',
                'price' => 19.00,
                'img' => '/images/Img05.jpg',
                'category_id' => 4,
                'SKU' => 'NK722',
                'material' => 'Metal',
                'dimensions' => '2cm x 2cm x 1cm',
                'weight' => '0.01kg',
                'colours' => 'Gold, Black',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 6,
                'title' => 'Yuki Hair Pin Set of 3',
                'currency' => '$',
                'price' => 29.00,
                'img' => '/images/Img06.jpg',
                'category_id' => 3,
                'SKU' => 'HS325',
                'material' => 'Metal',
                'dimensions' => '10cm x 1cm x 1cm',
                'weight' => '0.01kg',
                'colours' => 'Gold, Ruby',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 7,
                'title' => 'Luck With Heart',
                'currency' => '$',
                'price' => 129.40,
                'img' => '/images/Img07.jpg',
                'category_id' => 4,
                'SKU' => 'NK325',
                'material' => 'Metal',
                'dimensions' => '28cm x 4cm x 0.5cm',
                'weight' => '0.034kg',
                'colours' => 'Gold, Silver',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 8,
                'title' => 'Seleva',
                'currency' => '$',
                'price' => 245.70,
                'img' => '/images/Img08.jpg',
                'category_id' => 4,
                'SKU' => 'NK375',
                'material' => 'Metal',
                'dimensions' => '28cm x 3cm x 1cm',
                'weight' => '0.046kg',
                'colours' => 'Gold, White, Black',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 9,
                'title' => 'Zotov',
                'currency' => '$',
                'price' => 344.99,
                'img' => '/images/Img09.jpg',
                'category_id' => 7,
                'SKU' => 'PT3705',
                'material' => 'Metal, Zircon, Ceramics',
                'dimensions' => '3cm x 3cm x 0.4cm',
                'weight' => '0.026kg',
                'colours' => 'Gold, White, Black',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 10,
                'title' => 'Kamila',
                'currency' => '$',
                'price' => 245.70,
                'img' => '/images/Img10.jpg',
                'category_id' => 1,
                'SKU' => 'EL14',
                'material' => 'Metal',
                'dimensions' => '5cm x 3cm x 0.6cm',
                'weight' => '0.028kg',
                'colours' => 'Gold',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 11,
                'title' => 'BRUNY',
                'currency' => '$',
                'price' => 64.90,
                'img' => '/images/Img11.jpg',
                'category_id' => 4,
                'SKU' => 'NK4',
                'material' => 'Metal, Artificial Pearls',
                'dimensions' => '31cm x 3cm x 0.9cm',
                'weight' => '0.024kg',
                'colours' => 'Gold, White',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 12,
                'title' => 'Cherutty',
                'currency' => '$',
                'price' => 21.00,
                'img' => '/images/Img12.jpg',
                'category_id' => 5,
                'SKU' => 'CH19',
                'material' => 'Metal',
                'dimensions' => '21cm x 0.4cm x 0.4cm',
                'weight' => '0.014kg',
                'colours' => 'Gold',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 13,
                'title' => 'Hotei',
                'currency' => '$',
                'price' => 219.50,
                'img' => '/images/Img13.jpg',
                'category_id' => 1,
                'SKU' => 'EL21',
                'material' => 'Silver, Gold',
                'dimensions' => '5cm x 4cm x 0.3cm',
                'weight' => '0.011kg',
                'colours' => 'Gold, Silver',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 14,
                'title' => 'Quasar',
                'currency' => '$',
                'price' => 119.70,
                'img' => '/images/Img14.jpg',
                'category_id' => 2,
                'SKU' => 'HS03',
                'material' => 'Metal, Zircon',
                'dimensions' => '1.9cm x 1.5cm x 0.2cm',
                'weight' => '0.013kg',
                'colours' => 'Gold, Silver, White',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 15,
                'title' => 'Pabur',
                'currency' => '$',
                'price' => 14.00,
                'img' => '/images/Img15.jpg',
                'category_id' => 7,
                'SKU' => 'PT33',
                'material' => 'Artificial Pearls',
                'dimensions' => '1.9cm x 1.5cm x 0.2cm',
                'weight' => '0.013kg',
                'colours' => 'Gold, Silver, White',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 16,
                'title' => 'BOTTEGA VENETA',
                'currency' => '$',
                'price' => 514.00,
                'img' => '/images/Img16.jpg',
                'category_id' => 2,
                'SKU' => 'HP07',
                'material' => 'Silver, Gold',
                'dimensions' => '1.9cm x 0.9cm x 0.5cm',
                'weight' => '0.024kg',
                'colours' => 'Gold, Black',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 17,
                'title' => 'Yaroslavna',
                'currency' => '$',
                'price' => 101.50,
                'img' => '/images/Img17.jpg',
                'category_id' => 4,
                'SKU' => 'NK9107',
                'material' => 'Metal',
                'dimensions' => '29cm x 4cm x 0.5cm',
                'weight' => '0.024kg',
                'colours' => 'Gold, Silver',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 18,
                'title' => 'Dior',
                'currency' => '$',
                'price' => 171.50,
                'img' => '/images/Img18.jpg',
                'category_id' => 8,
                'SKU' => 'BT3205',
                'material' => 'Silver, Zircon',
                'dimensions' => '1.7cm x 0.7cm x 0.3cm',
                'weight' => '0.014kg',
                'colours' => 'Gold, White',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 19,
                'title' => 'Fashion Stories',
                'currency' => '$',
                'price' => 475.50,
                'img' => '/images/Img19.jpg',
                'category_id' => 4,
                'SKU' => 'NK3205',
                'material' => 'Silver, Amber',
                'dimensions' => '32cm x 5cm x 1cm',
                'weight' => '0.034kg',
                'colours' => 'Silver, Amber',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 20,
                'title' => 'Chanel',
                'currency' => '$',
                'price' => 70.50,
                'img' => '/images/Img20.webp',
                'category_id' => 1,
                'SKU' => 'EL05',
                'material' => 'Metal, Artificial Pearls',
                'dimensions' => '32cm x 5cm x 1cm',
                'weight' => '0.054kg',
                'colours' => 'Gold, White',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 21,
                'title' => 'Storg',
                'currency' => '$',
                'price' => 378.80,
                'img' => '/images/Img21.jpg',
                'category_id' => 2,
                'SKU' => 'HP4405',
                'material' => 'Steel, Bronze',
                'dimensions' => '2cm x 1cm x 0.3cm',
                'weight' => '0.021kg',
                'colours' => 'Silver, Bronze',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 22,
                'title' => 'Love Republic',
                'currency' => '$',
                'price' => 69.90,
                'img' => '/images/Img22.jpg',
                'category_id' => 1,
                'SKU' => 'EL1715',
                'material' => 'Metal',
                'dimensions' => '5cm x 1.5cm x 1.5cm',
                'weight' => '0.01kg',
                'colours' => 'Gold',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 23,
                'title' => 'Stone',
                'currency' => '$',
                'price' => 116.40,
                'img' => '/images/Img23.jpg',
                'category_id' => 5,
                'SKU' => 'CH11',
                'material' => 'Metal, Artificial Pearls',
                'dimensions' => '21cm x 0.5cm x 0.5cm',
                'weight' => '0.02kg',
                'colours' => 'White, Gold',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 24,
                'title' => 'Exclaim',
                'currency' => '$',
                'price' => 460.80,
                'img' => '/images/Img24.jpg',
                'category_id' => 1,
                'SKU' => 'EL6711',
                'material' => 'Silver, Gold',
                'dimensions' => '7cm x 4cm x 0.2cm',
                'weight' => '0.014kg',
                'colours' => 'Gold',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 25,
                'title' => 'Carolina',
                'currency' => '$',
                'price' => 17.20,
                'img' => '/images/Img25.jpg',
                'category_id' => 4,
                'SKU' => 'NK012',
                'material' => 'Metal',
                'dimensions' => '29cm x 4cm x 0.6cm',
                'weight' => '0.031kg',
                'colours' => 'Gold',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 26,
                'title' => 'Stingy',
                'currency' => '$',
                'price' => 163.00,
                'img' => '/images/Img26.jpg',
                'category_id' => 6,
                'SKU' => 'BE0201',
                'material' => 'Metal, Artificial Pearls',
                'dimensions' => '29cm x 1cm x 1cm',
                'weight' => '0.04kg',
                'colours' => 'White, Gold',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 27,
                'title' => 'Perles',
                'currency' => '$',
                'price' => 13.99,
                'img' => '/images/Img27.jpg',
                'category_id' => 1,
                'SKU' => 'EL017',
                'material' => 'Metal',
                'dimensions' => '4cm x 3cm x 0.2cm',
                'weight' => '0.01kg',
                'colours' => 'Gold',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 28,
                'title' => 'Beautiful Today',
                'currency' => '$',
                'price' => 599.99,
                'img' => '/images/Img28.jpg',
                'category_id' => 1,
                'SKU' => 'EL1017',
                'material' => 'Gold, Crystal',
                'dimensions' => '4cm x 3cm x 0.8cm',
                'weight' => '0.025kg',
                'colours' => 'White, Gold',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 29,
                'title' => 'Le Cher',
                'currency' => '$',
                'price' => 199.99,
                'img' => '/images/Img29.jpg',
                'category_id' => 6,
                'SKU' => 'BE3114',
                'material' => 'Metal, Artificial Pearls',
                'dimensions' => '4cm x 3cm x 0.8cm',
                'weight' => '0.055kg',
                'colours' => 'White, Gold',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 30,
                'title' => 'LAVEREDO',
                'currency' => '$',
                'price' => 157.00,
                'img' => '/images/Img30.png',
                'category_id' => 1,
                'SKU' => 'EL3810',
                'material' => 'Silver, Gold',
                'dimensions' => '4.7cm x 2.5cm x 0.2cm',
                'weight' => '0.015kg',
                'colours' => 'Gold',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 31,
                'title' => 'Graff',
                'currency' => '$',
                'price' => 399.99,
                'img' => '/images/Img31.jpg',
                'category_id' => 1,
                'SKU' => 'EL3710',
                'material' => 'Silver, Gold, Zircon',
                'dimensions' => '3.7cm x 2.4cm x 0.5cm',
                'weight' => '0.025kg',
                'colours' => 'Gold, White',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 32,
                'title' => 'Seashell',
                'currency' => '$',
                'price' => 19.99,
                'img' => '/images/Img32.jpg',
                'category_id' => 4,
                'SKU' => 'NK190',
                'material' => 'Metal',
                'dimensions' => '33cm x 4cm x 0.4cm',
                'weight' => '0.02kg',
                'colours' => 'Gold',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 33,
                'title' => 'Appup',
                'currency' => '$',
                'price' => 17.99,
                'img' => '/images/Img33.jpg',
                'category_id' => 4,
                'SKU' => 'NK1092',
                'material' => 'Metal',
                'dimensions' => '34cm x 1cm x 1cm',
                'weight' => '0.031kg',
                'colours' => 'Gold',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
            [
                'id' => 34,
                'title' => 'Romashka',
                'currency' => '$',
                'price' => 599.99,
                'img' => '/images/Img34.jpg',
                'category_id' => 1,
                'SKU' => 'EL017',
                'material' => 'Gold, Perl',
                'dimensions' => '3cm x 2cm x 0.6cm',
                'weight' => '0.025kg',
                'colours' => 'White, Gold',
                'description' => "Elegant handcrafted jewelry piece made from high-quality materials. Perfect for everyday wear and special occasions. Lightweight design with lasting finish.",
            ],
        ];

        foreach ($products as $p) {
            DB::table('products')->updateOrInsert(
                ['id' => $p['id']], // сохраняем те же id, как в фронтенде
                [
                    'title' => $p['title'],
                    'sku' => $p['SKU'],
                    'category_id' => $p['category_id'],
                    'price' => $p['price'],
                    'currency' => $p['currency'],
                    'description' => $p['description'],
                    'img' => $p['img'],
                    'weight' => $p['weight'],
                    'dimensions' => $p['dimensions'] ?? $p['dimentions'] ?? null,
                    'colours' => $p['colours'],
                    'material' => $p['material'],
                    'created_at' => $now,
                    'updated_at' => $now,
                ]
            );
        }
    }
}
